### PR TITLE
Add examples to README file

### PR DESCRIPTION
**Pull request by mrava87**

### CODE REVIEW

**Comment by pgdr** [comment]
Hi, and thanks for the contribution!  If you annotate which language is used for your code snippets in markdown, you get appropriate syntax highlighting.

```
    ```python
    def myfun(no, args):
        do_something();
        assert no is not None
    ```
```


Compare
```
def myfun(no, args):
   do_something();
   assert no is not None
```

with

```python
def myfun(no, args):
   do_something();
   assert no is not None
```

**Comment by mrava87** [comment]
Hi Pål,
that's very useful, I didn't know. I will use it from now on when I add things to documentation 😁

Cheers
iMR

**Comment by mrava87** [comment]
Btw, shall I do it and make new merge request or you adding them for this one?

iMR

**Comment by pgdr** [comment]
You can just add them to this one as a new commit.

**Comment by mrava87** [comment]
Done now, let me know if this is ok. Apparently matlab annotation is not supported by markdown so I only did it for python

**Pull request merged**
