### PR TITLE
Trying to move the python code to be py3k compatible

### PR DESCRIPTION
**Pull request by asbjorn**
More Python 3.X changes to the python code

### CODE REVIEW

**Comment by pgdr** [comment]
Then we should add `from builtins import range` or something similar to maintain `xrange`-behavior.

**Comment by jokva** [comment]
Something like that. The range function itself isn't so bad (the lists are never *that* big and they don't strictly require generator behaviour - the `izip`s do.

**Comment by jokva** [comment]
That being said, thanks for this effort! Are you trying to run it with python3? What other problems have you faced?

**Comment by asbjorn** [comment]
@pgdr: Yes, to get the `range` backported to Python 2.X the `builtins.range` can be really handy.

You will need to update the requirements.txt file for that though - but, still :+1: 

Will that work for both Python 2.X or Python 3.X or do you need to do a check like this:
```import sys
if sys.version_info < (3.0):
    from builtins import range
```

**Pull request merged**
