### PR TITLE
cppcheck support

### PR DESCRIPTION
**Pull request by jokva**
Gonna be some noise here (sorry in advance), so please turn off notifications.

### CODE REVIEW

**Comment by jokva** [comment]
This can be reviewed now, but the tests will fail because there's no precise package for cppcheck 1.77. I'll restart the CI once the package is ready.

**Comment by jokva** [comment]
Packages for precise are up, so tests should pass now.

**Comment by pgdr** [comment]
I don't know if we want that for this project, but it _is possible_ to run Travis with Ubuntu 14.04.

**Comment by jokva** [comment]
I suppose 12.-series compatibility is nice, but apparently using trusty sometimes give rise to other problems. A previous iteration of this patch ran on trusty, but now we can run on both trusty and precise.

**Comment by jokva** [comment]
Thanks, much appreciated.

**Pull request merged**
